# tasks file for haproxy
---
- name: install | installing haproxy
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ haproxy_dependencies }}"
  tags:
    - haproxy-install-dependencies

- name: install | generate dhparams
  shell: openssl dhparam -out /etc/haproxy/dhparams.pem 4096
  when: haproxy_global_dhparams|bool
